(require '[clojure.reflect :as r])
(import '[org.ejml.simple SimpleMatrix])

(def m (SimpleMatrix. 3 3 true (float-array [1 0 0 0 2 0 0 0 4])))
(def v (SimpleMatrix. 3 1 true (float-array [1 2 3])))
(map :name (:members (r/reflect m)))
(.normF v)
(.plus v v)
(.invert m)
(.mult m v)
(.scale m 2.0)
(.transpose m)
(.getRow m 0)
(.getColumn m 0)
(.get m 1 1)
(.dot v v)
(.determinant m)
